version: "3"

services:
  docker-cmpd:
    image: cadcuceus/cmp-chain-mainnet-node
    container_name: cmpd-mainnet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ID=0
      - READ-TIMEOUT=60
      - WRITE-TIMEOUNT=60  
    restart: "no"
    ports:
      - "26656:26656"
      - "8545:8545" 
    volumes:
      - ./node-data:/cmp
