version: "3.9"

services:
  docker-cmpd:
    image: caduceus/cmp-chain-mainnet-node:1.0.11
    container_name: cmp-mainnet-node
    environment:
      - ID=0
      - READ-TIMEOUT=60
      - WRITE-TIMEOUNT=60 
      - ENABLE-CROSS-DOMAIN=true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 100
        window: 120s
    ports:
      - "26656:26656"
      - "26658:8545" 
    volumes:
      - ./node-data:/cmp
