version: "3.9"

services:
  db:
    image: caduceus/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql2022
      MYSQL_DATABASE: cmp_chain
    ports:
      - "3306:3306"
    volumes:
      -  ./node-data/mysql/data:/var/lib/mysql
  logs:
    image: caduceus/blockchain-event-plugin:1.0.2
    environment:
      RPC_PORT: 18535
      MysqlSourceName: 'root:mysql2022@tcp(db:3306)/cmp_chain?parseTime=true&charset=utf8&loc=Local'

  docker-cmpd:
    image: caduceus/cmp-chain-mainnet-node:logs-1
    container_name: cmp-mainnet-node
    environment:
      - ID=0
      - READ-TIMEOUT=60
      - WRITE-TIMEOUNT=60 
      - ENABLE-CROSS-DOMAIN=true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 100
        window: 120s
    ports:
      - "26656:26656"
      - "26658:8545" 
      - "26660:8546"
    volumes:
      - ./node-data:/cmp


  

