version: "3.9"

services:
  docker-cmpd:
    image: cadcuceus/cmp-chain-mainnet-node:1.0.5
    container_name: cmp-mainnet-node
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ID=0
      - READ-TIMEOUT=60
      - WRITE-TIMEOUNT=60  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 100
        window: 120s
    ports:
      - "26656:26656"
      - "8545:8545" 
    volumes:
      - ./node-data:/cmp
